name: todo_list
description: A Multi-Platform Sync Enabled Todo List App

publish_to: 'none'
version: 1.2.0+4

environment:
  sdk: ^3.8.1
  flutter: 3.32.6

dependencies:
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/