name: todo_list
description: A Multi-Platform Sync Enabled Todo List App

publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/