display_name: Todo List
icon: snap/gui/todo-list.png

keywords:
  - Todo
  - Productivity
  - Task Management
  - To-Do List

generic_name: Todo List
categories:
  - Productivity
  - Utilities

startup_notify: true