// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL28gz1K02y94nTu7gsHNCgACPtBlbtLM',
    appId: '1:535575396228:web:5fa3dd33056125b85a67d1',
    messagingSenderId: '535575396228',
    projectId: 'todo-list-bd0d3',
    authDomain: 'todo-list-bd0d3.firebaseapp.com',
    storageBucket: 'todo-list-bd0d3.firebasestorage.app',
    measurementId: 'G-7SM53M5V61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI77r3gZhzsp411jErWJO8dRBj_EuKvfM',
    appId: '1:535575396228:android:6c0416b2e9e7a0675a67d1',
    messagingSenderId: '535575396228',
    projectId: 'todo-list-bd0d3',
    storageBucket: 'todo-list-bd0d3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL28gz1K02y94nTu7gsHNCgACPtBlbtLM',
    appId: '1:535575396228:web:3d1eb44edc95f5b55a67d1',
    messagingSenderId: '535575396228',
    projectId: 'todo-list-bd0d3',
    authDomain: 'todo-list-bd0d3.firebaseapp.com',
    storageBucket: 'todo-list-bd0d3.firebasestorage.app',
    measurementId: 'G-1TXRNP2CK9',
  );

}